name: Publish package

on:
  push:
    tags: ['*']

permissions:
  attestations: write
  id-token: write
  packages: write
  security-events: write

jobs:
  publish-package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - id: publish-package
        name: Publish package
        uses: nedix/actions/publish-package@main
        with:
          platforms: linux/amd64,linux/arm64/v8
          registry: ${{ secrets.REGISTRY_DOMAIN }}
          registry_path: ${{ secrets.REGISTRY_PATH }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
