name: Publish package

on:
  push:
    tags: ['*']

jobs:
  publish-package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - id: publish-package
        name: Publish package
        uses: nedix/actions/publish-package@main
        with:
          enable_cache: 'true'
          platforms: linux/amd64,linux/arm64/v8
          registry: ${{ secrets.REGISTRY_DOMAIN || 'ghcr.io' }}
          registry_path: ${{ secrets.REGISTRY_PATH || github.repository }}
          registry_username: ${{ secrets.REGISTRY_USERNAME || github.actor }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD || github.token }}
